baseurl = "https://portfolio.r09i.me/"
title = "tkchry"
theme = "hugo-coder"
languagecode = "ja"
defaultcontentlanguage = "ja"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = ""

[params]
author = "Ryo Takeuchi"
info = "Android Application Developer"
description = "Ryo Takeuchi's personal website"
keywords = "blog,developer,personal"
avatarurl = "images/avatar.png"

#favicon_32 = "/img/favicon-32x32.png"
#favicon_16 = "/img/favicon-16x16.png"

since = 2022

enableTwemoji = true

colorScheme = "auto"
hidecolorschemetoggle = false

#customCSS = ["css/custom.css"]
#customSCSS = ["scss/custom.scss"]
#customJS = ["js/custom.js"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/tkchry/"
[[params.social]]
name = "Twitter"
icon = "fa fa-twitter fa-2x"
weight = 2
url = "https://twitter.com/tkchry/"

# Menu links
[[menu.main]]
name = "About"
weight = 1
url = "about/"
[[menu.main]]
name = "Blog"
weight = 2
url  = "posts/"
